const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={worksheets:'lernai_worksheets_v2',saved:'lernai_saved_v2',minutes:'lernai_minutes_v2',quiz:'lernai_quiz_v2',recent:'lernai_recent_v2',theme:'lernai_theme_v2'};
let worksheets=load(store.worksheets,[]),saved=load(store.saved,[]),minutes=Number(localStorage.getItem(store.minutes)||0),quizHistory=load(store.quiz,[]),recent=load(store.recent,[]),currentQuiz=[],quizIndex=0,quizScore=0,currentWs=null;
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}} function persist(){localStorage.setItem(store.worksheets,JSON.stringify(worksheets));localStorage.setItem(store.saved,JSON.stringify(saved));localStorage.setItem(store.minutes,minutes);localStorage.setItem(store.quiz,JSON.stringify(quizHistory));localStorage.setItem(store.recent,JSON.stringify(recent))} function escapeHtml(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function updateProgress(){const goal=60;$('#studyMinutes').textContent=minutes+' Min.';$('#studyProgress').style.width=Math.min(100,minutes/goal*100)+'%';$('#statMinutes').textContent=minutes;$('#statWorksheets').textContent=worksheets.length;$('#statQuiz').textContent=quizHistory.length;const p=Math.min(100,Math.round((minutes/goal)*70+(quizHistory.length?15:0)+(worksheets.length?15:0)));$('#bigProgress').style.width=p+'%';$('#progressLabel').textContent=p+'%'}
function addMinutes(n=1){minutes+=n;persist();updateProgress()}
function addRecent(type,title){recent.unshift({type,title,date:new Date().toLocaleDateString('de-DE')});recent=recent.slice(0,6);persist()}
function showApp(){if($('#landing'))$('#landing').classList.add('hidden');$('#app').classList.remove('hidden')}
function showView(name){showApp();$$('.view').forEach(v=>v.classList.remove('active'));$('#'+name+'View').classList.add('active');$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#viewTitle').textContent={dashboard:'Übersicht',chat:'Lernchat',worksheets:'Arbeitsblätter',quiz:'Quiz',saved:'Meine Materialien'}[name]||name;renderAll();$('#sidebar').classList.remove('open')}
function openChat(){showView('chat');$('#chatInput').focus()}
$('#startLearning')?.addEventListener('click',showApp);$('#startLearning2')?.addEventListener('click',()=>showView('dashboard'));$('#demoBtn')?.addEventListener('click',()=>{showView('chat');$('#chatInput').value='Erkläre mir, wie LernAI funktioniert.';$('#chatForm').requestSubmit()});
$$('.nav-item[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#newChatBtn').onclick=()=>{showView('chat');$('#messages').innerHTML='<div class="welcome"><div class="sparkle">✦</div><h1>Was möchtest du lernen?</h1><p>Starte eine neue Lernsession.</p></div>'};$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem(store.theme,document.documentElement.classList.contains('light')?'light':'dark')};if(localStorage.getItem(store.theme)==='light')document.documentElement.classList.add('light');
function routeAction(a){if(a==='chat')openChat();if(a==='worksheet')$('#worksheetDialog').showModal();if(a==='quiz')$('#quizDialog').showModal();if(a==='graph')graphMessage();if(a==='explain'){openChat();$('#chatInput').value='Erkläre mir mein Thema besonders einfach, Schritt für Schritt, mit einem Beispiel.';}}
$$('[data-action]').forEach(b=>b.onclick=()=>routeAction(b.dataset.action));$$('[data-prompt]').forEach(b=>b.onclick=()=>{openChat();$('#chatInput').value=b.dataset.prompt;$('#chatForm').requestSubmit()});
$('#chatForm').onsubmit=async e=>{e.preventDefault();const text=$('#chatInput').value.trim();if(!text)return;addMessage(text,'user');$('#chatInput').value='';addMinutes(1);addRecent('Chat',text.slice(0,55));if(/arbeitsblatt/i.test(text)){addMessage('Ich öffne den Arbeitsblatt-Generator. Du kannst Thema, Fach und Schwierigkeit festlegen.','ai');$('#wsTopic').value=text.replace(/.*arbeitsblatt(?: zu| über)?/i,'').trim()||'';$('#worksheetDialog').showModal();return}if(/\bquiz\b/i.test(text)){addMessage('Ich öffne den Quiz-Generator für dich.','ai');$('#quizTopic').value=text.replace(/.*quiz(?: zu| über)?/i,'').trim()||'';$('#quizDialog').showModal();return}const loading=addMessage('Ich denke kurz nach …','ai');try{const history=[...$$('#messages .message')].slice(-10).map(m=>({role:m.classList.contains('user')?'user':'assistant',content:m.querySelector('.bubble')?.textContent||''}));const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history})});const data=await r.json();if(!r.ok)throw Error(data.error||'KI-Fehler');loading.querySelector('.bubble').innerHTML=formatAnswer(data.answer||'Keine Antwort erhalten.')}catch(err){loading.querySelector('.bubble').textContent='Die KI-Verbindung ist gerade nicht verfügbar. '+(err.message||'Bitte prüfe später die API-Konfiguration.')}};
function formatAnswer(t){return escapeHtml(t).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}
function addMessage(text,type){const wrap=document.createElement('div');wrap.className='message '+type;wrap.innerHTML=type==='ai'?'<div class="avatar">✦</div><div class="bubble"></div>':'<div class="bubble"></div>';if(type==='ai')wrap.querySelector('.bubble').textContent=text;else wrap.querySelector('.bubble').textContent=text;$('#messages').appendChild(wrap);$('#messages').scrollTop=$('#messages').scrollHeight;return wrap}
function graphMessage(){openChat();const msg=addMessage('Ich kann Lerninhalte als einfache Diagramme, Zeitstrahlen, Mindmaps oder mathematische Darstellungen aufbereiten. Beschreibe einfach das Thema und die gewünschte Grafik.','ai');msg.querySelector('.bubble').innerHTML='<b>📊 Grafikmodus</b><br>Beschreibe z. B. „Erstelle mir einen Zeitstrahl zur Französischen Revolution“.'}
$('#createWorksheet').onclick=()=>$('#worksheetDialog').showModal();
$('#worksheetForm').onsubmit=async e=>{e.preventDefault();const topic=$('#wsTopic').value.trim(),subject=$('#wsSubject').value,level=$('#wsLevel').value,klass=$('#wsClass').value,count=Number($('#wsCount').value),solutions=$('#wsSolutions').checked;const btn=e.submitter;btn.disabled=true;btn.textContent='⏳ KI erstellt …';try{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'worksheet',topic,subject,level,klass,count,solutions})});const data=await r.json();if(!r.ok)throw Error(data.error||'Fehler');const ws={id:Date.now(),title:data.title||topic,subject,level,klass,count,content:data.content||makeWorksheet(topic,subject,level,count),solutions:data.solutions||''};worksheets.unshift(ws);persist();addRecent('Arbeitsblatt',ws.title);$('#worksheetDialog').close();openEditor(ws)}catch(err){const ws={id:Date.now(),title:topic,subject,level,klass,count,content:makeWorksheet(topic,subject,level,count),solutions:''};worksheets.unshift(ws);persist();$('#worksheetDialog').close();openEditor(ws);alert('Die KI war nicht erreichbar. Es wurde eine bearbeitbare Vorlage erstellt.')}finally{btn.disabled=false;btn.textContent='✨ Mit KI erstellen'}};
function makeWorksheet(topic,subject,level,count){let out='<h1>'+escapeHtml(topic)+'</h1><p><b>Fach:</b> '+escapeHtml(subject)+' · <b>Klasse:</b> '+escapeHtml($('#wsClass')?.value||'')+' · <b>Schwierigkeit:</b> '+escapeHtml(level)+'</p><hr><p>Bearbeite die Aufgaben und erkläre deine Lösungswege.</p>';for(let i=1;i<=count;i++)out+='<h3>'+i+'. Aufgabe</h3><p>Erstelle eine passende Aufgabe zum Thema <b>'+escapeHtml(topic)+'</b> und bearbeite sie hier.</p><p>________________________________________________________________</p><p>________________________________________________________________</p>';return out}
function openEditor(ws){currentWs=ws;$('#editorTitle').value=ws.title;$('#editor').innerHTML=ws.content;$('#editorDialog').showModal()}
$('#saveEditor').onclick=()=>{if(!currentWs)return;currentWs.title=$('#editorTitle').value.trim()||currentWs.title;currentWs.content=$('#editor').innerHTML;persist();addRecent('Bearbeitet',currentWs.title);$('#editorDialog').close();renderAll()};$('#closeEditor').onclick=()=>$('#editorDialog').close();$('#exportEditor').onclick=()=>exportDocument(currentWs);$$('[data-cmd]').forEach(b=>b.onclick=()=>document.execCommand(b.dataset.cmd,false,null));$('#addPage').onclick=()=>$('#editor').insertAdjacentHTML('beforeend','<div class="page-break"></div><h2>Neue Seite</h2><p></p>');
function exportDocument(ws){if(!ws)return;const html='<!doctype html><html lang="de"><meta charset="utf-8"><title>'+escapeHtml(ws.title)+'</title><style>body{font-family:Arial,sans-serif;max-width:760px;margin:40px auto;line-height:1.6}h1,h2,h3{color:#172033}.page-break{page-break-before:always}</style>'+ws.content+'</html>';const blob=new Blob([html],{type:'text/html'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=ws.title.replace(/[^a-z0-9äöüß]+/gi,'-')+'.html';a.click();URL.revokeObjectURL(a.href)}
function renderWorksheets(){const el=$('#worksheetList');el.innerHTML=worksheets.length?worksheets.map(w=>'<article class="card"><span class="eyebrow">'+escapeHtml(w.subject)+'</span><h3>'+escapeHtml(w.title)+'</h3><p>'+escapeHtml(w.level)+' · '+w.count+' Aufgaben · Klasse '+escapeHtml(w.klass||'')+'</p><div class="card-actions"><button class="secondary" onclick="openEditor(worksheets.find(x=>x.id==='+w.id+'))">Bearbeiten</button><button class="secondary" onclick="saveItem('+w.id+')">⭐ Speichern</button></div></article>').join(''):'<div class="card"><h3>Noch keine Arbeitsblätter</h3><p>Erstelle dein erstes KI-Arbeitsblatt.</p></div>'}
function saveItem(id){const w=worksheets.find(x=>x.id===id);if(w&&!saved.some(x=>x.id===id)){saved.push({...w});persist();renderAll()}}
function renderSaved(){const el=$('#savedList');el.innerHTML=saved.length?saved.map(w=>'<article class="card"><span class="eyebrow">GESPEICHERT</span><h3>'+escapeHtml(w.title)+'</h3><p>'+escapeHtml(w.subject)+' · '+escapeHtml(w.level)+'</p><button class="secondary" onclick="openEditor(worksheets.find(x=>x.id==='+w.id+'))">Öffnen</button></article>').join(''):'<div class="card"><h3>Deine Sammlung ist noch leer</h3><p>Speichere Materialien, die du später weiterbearbeiten möchtest.</p></div>'}
$('#createQuiz').onclick=()=>$('#quizDialog').showModal();$('#quizForm').onsubmit=async e=>{e.preventDefault();const topic=$('#quizTopic').value.trim(),subject=$('#quizSubject').value,count=Number($('#quizCount').value),btn=e.submitter;btn.disabled=true;btn.textContent='⏳ Erstelle …';try{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'quiz',topic,subject,count})});const data=await r.json();if(!r.ok)throw Error(data.error||'Fehler');currentQuiz=data.questions||[];$('#quizDialog').close();showView('quiz');quizIndex=0;quizScore=0;addRecent('Quiz',topic);renderQuestion()}catch{currentQuiz=makeFallbackQuiz(topic);$('#quizDialog').close();showView('quiz');quizIndex=0;quizScore=0;renderQuestion()}finally{btn.disabled=false;btn.textContent='🧠 Quiz erstellen'}};
function makeFallbackQuiz(topic){return[{q:'Welche Aussage passt am besten zu '+topic+'?',o:['Eine zufällige Aussage','Eine grundlegende Aussage zum Thema','Eine Aussage ohne Bezug','Keine der Antworten'],a:1,e:'Die zweite Antwort ist die passende allgemeine Aussage.'},{q:'Wie lernt man ein neues Thema besonders gut?',o:['Nur einmal lesen','Aktiv erklären und üben','Gar nicht wiederholen','Nur Überschriften anschauen'],a:1,e:'Aktives Abrufen und Üben unterstützt das Lernen.'},{q:'Was solltest du bei Unsicherheit tun?',o:['Aufgeben','Nachfragen und prüfen','Raten und vergessen','Nichts notieren'],a:1,e:'Nachfragen und Prüfen hilft beim Verständnis.'}]}
function renderQuestion(){const area=$('#quizArea');if(!currentQuiz.length){area.innerHTML='<div class="quiz-card"><h2>Erstelle dein erstes Quiz 🧠</h2><p>Wähle oben ein Thema und die Anzahl der Fragen.</p></div>';return}if(quizIndex>=currentQuiz.length){area.innerHTML='<div class="quiz-card result"><div class="result-icon">✓</div><span class="eyebrow">AUSWERTUNG</span><h2>Quiz abgeschlossen</h2><p>Du hast <b>'+quizScore+' von '+currentQuiz.length+'</b> Fragen richtig beantwortet.</p><div class="score-bar"><i style="width:'+(quizScore/currentQuiz.length*100)+'%"></i></div><button class="primary" id="newQuizFromResult">Neues Quiz</button></div>';quizHistory.push({score:quizScore,total:currentQuiz.length,date:new Date().toISOString()});persist();addMinutes(3);document.getElementById('newQuizFromResult')?.addEventListener('click',()=>$('#quizDialog').showModal());return}const q=currentQuiz[quizIndex];area.innerHTML='<div class="quiz-card"><span class="eyebrow">FRAGE '+(quizIndex+1)+' / '+currentQuiz.length+'</span><div class="quiz-progress"><i style="width:'+((quizIndex)/currentQuiz.length*100)+'%"></i></div><h2>'+escapeHtml(q.q)+'</h2>'+q.o.map((x,i)=>'<button class="option" onclick="answerQuiz('+i+',this)">'+escapeHtml(x)+'</button>').join('')+'<p id="feedback" class="feedback"></p></div>'}
function answerQuiz(i,btn){const q=currentQuiz[quizIndex];$$('.option').forEach(b=>b.disabled=true);const fb=$('#feedback');if(i===Number(q.a)){btn.classList.add('correct');quizScore++;fb.textContent='✓ Richtig! '+(q.e||'Gut gemacht.');}else{btn.classList.add('wrong');const opts=$$('.option');opts[Number(q.a)]?.classList.add('correct');fb.textContent='Noch nicht. '+(q.e||'Schau dir die richtige Antwort noch einmal an.')}setTimeout(()=>{quizIndex++;renderQuestion()},1100)}
function renderDashboard(){const list=$('#recentList');list.innerHTML=recent.length?recent.map(x=>'<div class="recent-item"><span>'+({Chat:'💬',Arbeitsblatt:'📄',Quiz:'🧠',Bearbeitet:'✏️'}[x.type]||'•')+'</span><div><b>'+escapeHtml(x.title)+'</b><small>'+escapeHtml(x.type)+' · '+escapeHtml(x.date)+'</small></div></div>').join(''):'<p class="muted">Noch keine Lernaktivität.</p>'}
function renderAll(){updateProgress();renderWorksheets();renderSaved();renderDashboard()}renderAll();