const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let worksheets=JSON.parse(localStorage.getItem('lernai_worksheets')||'[]'), saved=JSON.parse(localStorage.getItem('lernai_saved')||'[]'), minutes=Number(localStorage.getItem('lernai_minutes')||0);
const tips=['Erkläre dir ein Thema laut in eigenen Worten – das zeigt schnell, was du schon verstanden hast.','Lerne in kleinen Einheiten und teste dich danach ohne Unterlagen.','Fehler sind Lernsignale: Lass dir erklären, warum eine Antwort falsch war.','Nutze Arbeitsblätter zum Üben und den Chat zum Nachfragen.'];
$('#tipText').textContent=tips[Math.floor(Math.random()*tips.length)];
$('#studyMinutes').textContent=minutes+' Min.'; $('#studyProgress').style.width=Math.min(100,minutes/60*100)+'%';

function persist(){localStorage.setItem('lernai_worksheets',JSON.stringify(worksheets));localStorage.setItem('lernai_saved',JSON.stringify(saved));localStorage.setItem('lernai_minutes',minutes)}
function addMinutes(n=1){minutes+=n;$('#studyMinutes').textContent=minutes+' Min.';$('#studyProgress').style.width=Math.min(100,minutes/60*100)+'%';persist()}
function showView(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+name+'View').classList.add('active');$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#viewTitle').textContent={chat:'Lernchat',worksheets:'Arbeitsblätter',quiz:'Quiz',saved:'Gespeichert'}[name];renderAll()}
$$('.nav-item[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
$('#newChatBtn').onclick=()=>{showView('chat');$('#messages').innerHTML='<div class="welcome"><div class="sparkle">✦</div><h1>Was möchtest du heute lernen?</h1><p>Starte eine neue Lernsession.</p></div>';};
$('#themeBtn').onclick=()=>document.documentElement.classList.toggle('light');
$$('[data-prompt]').forEach(b=>b.onclick=()=>{ $('#chatInput').value=b.dataset.prompt; $('#chatForm').requestSubmit(); });
$$('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='worksheet')$('#worksheetDialog').showModal();if(b.dataset.action==='quiz')startQuiz();if(b.dataset.action==='graph')addGraphMessage();if(b.dataset.action==='explain'){$('#chatInput').value='Erkläre mir mein Thema besonders einfach, Schritt für Schritt, mit einem Beispiel.';$('#chatInput').focus();}});
$('#chatForm').onsubmit=async e=>{e.preventDefault();const text=$('#chatInput').value.trim();if(!text)return;addMessage(text,'user');$('#chatInput').value='';addMinutes(1);const lower=text.toLowerCase();if(lower.includes('arbeitsblatt')){addMessage('Klar! Ich öffne den Arbeitsblatt-Generator. Du kannst dort Thema, Fach und Schwierigkeit festlegen.','ai');$('#worksheetDialog').showModal();return}if(lower.includes('quiz')){addMessage('Sehr gerne! Ich starte ein interaktives Quiz.','ai');startQuiz();return}const loading=addMessage('Ich denke kurz nach …','ai');try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});if(!r.ok)throw Error();const data=await r.json();loading.querySelector('.bubble').textContent=data.answer||fallback(text)}catch{loading.querySelector('.bubble').textContent=fallback(text)}};
function addMessage(text,type){const wrap=document.createElement('div');wrap.className='message '+type;wrap.innerHTML=type==='ai'?'<div class="avatar">✦</div><div class="bubble"></div>':'<div class="bubble"></div>';wrap.querySelector('.bubble').textContent=text;$('#messages').appendChild(wrap);$('#messages').scrollTop=$('#messages').scrollHeight;return wrap}
function fallback(t){return 'Ich kann dir dieses Thema aufbereiten. Für echte KI-Antworten verbinde die App mit dem vorgesehenen /api/ai-Endpunkt. Du kannst mir zum Beispiel sagen: „Erkläre '+t+' einfach, Schritt für Schritt, mit einem Beispiel.“';}
function addGraphMessage(){addMessage('📊 Interaktive Grafik: Für dieses Thema kann die KI später automatisch eine passende Darstellung erzeugen. Die Oberfläche ist bereits vorbereitet.','ai')}

$('#worksheetForm').onsubmit=e=>{e.preventDefault();const ws={id:Date.now(),title:$('#wsTopic').value,subject:$('#wsSubject').value,level:$('#wsLevel').value,count:Number($('#wsCount').value),content:makeWorksheet($('#wsTopic').value,$('#wsSubject').value,$('#wsLevel').value,Number($('#wsCount').value))};worksheets.unshift(ws);persist();$('#worksheetDialog').close();openEditor(ws);};
$('#createWorksheet').onclick=()=>$('#worksheetDialog').showModal();
function makeWorksheet(topic,subject,level,count){let out='<h1>'+escapeHtml(topic)+'</h1><p><b>Fach:</b> '+subject+' &nbsp; <b>Schwierigkeit:</b> '+level+'</p><hr><p>Bearbeite die folgenden Aufgaben. Schreibe deine Lösungen direkt auf dieses Arbeitsblatt.</p>';for(let i=1;i<=count;i++)out+='<h3>'+i+'. Aufgabe</h3><p>Bearbeite eine passende Aufgabe zum Thema <b>'+escapeHtml(topic)+'</b>.</p><p>__________________________________________________________________</p><p>__________________________________________________________________</p>';out+='<hr><p><b>Selbstkontrolle:</b> Was konnte ich schon gut? Was möchte ich noch üben?</p>';return out}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function openEditor(ws){$('#editorTitle').value=ws.title;$('#editor').innerHTML=ws.content;$('#editorDialog').showModal();$('#saveEditor').onclick=()=>{ws.title=$('#editorTitle').value;ws.content=$('#editor').innerHTML;persist();$('#editorDialog').close();renderAll()};$('#exportEditor').onclick=()=>exportHtml(ws);$('#closeEditor').onclick=()=>$('#editorDialog').close()}
$$('[data-cmd]').forEach(b=>b.onclick=()=>document.execCommand(b.dataset.cmd,false,null));
function exportHtml(ws){const blob=new Blob(['<!doctype html><html lang="de"><meta charset="utf-8"><title>'+escapeHtml(ws.title)+'</title><style>body{font-family:Arial;max-width:760px;margin:40px auto;line-height:1.6}</style>'+ws.content+'</html>'],{type:'text/html'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=ws.title.replace(/[^a-z0-9äöüß]+/gi,'-')+'.html';a.click();URL.revokeObjectURL(a.href)}
function renderWorksheets(){const el=$('#worksheetList');el.innerHTML=worksheets.length?worksheets.map(w=>'<article class="card"><span class="eyebrow">'+w.subject+'</span><h3>'+escapeHtml(w.title)+'</h3><p>'+w.level+' · '+w.count+' Aufgaben</p><div class="card-actions"><button class="secondary" onclick="openEditor(worksheets.find(x=>x.id==='+w.id+'))">Bearbeiten</button><button class="secondary" onclick="saveItem('+w.id+')">⭐ Speichern</button></div></article>').join(''):'<div class="card"><h3>Noch keine Arbeitsblätter</h3><p>Erstelle dein erstes Arbeitsblatt – direkt hier im Browser bearbeitbar.</p></div>'}
function saveItem(id){const w=worksheets.find(x=>x.id===id);if(w&&!saved.some(x=>x.id===id)){saved.push(w);persist();renderAll()}}
function renderSaved(){const el=$('#savedList');el.innerHTML=saved.length?saved.map(w=>'<article class="card"><span class="eyebrow">GESPEICHERT</span><h3>'+escapeHtml(w.title)+'</h3><p>'+w.subject+' · '+w.level+'</p><button class="secondary" onclick="openEditor(worksheets.find(x=>x.id==='+w.id+'))">Öffnen</button></article>').join(''):'<div class="card"><h3>Deine Sammlung ist noch leer</h3><p>Speichere Arbeitsblätter, die du später weiterbearbeiten möchtest.</p></div>'}
let quizIndex=0,quizScore=0,quizQuestions=[];
function startQuiz(){showView('quiz');quizIndex=0;quizScore=0;quizQuestions=[{q:'Was ist 7 × 8?',o:['48','56','64','54'],a:1},{q:'Welche Einheit wird für elektrische Spannung verwendet?',o:['Ampere','Ohm','Volt','Watt'],a:2},{q:'Wie nennt man den Vorgang, bei dem Pflanzen Lichtenergie nutzen?',o:['Verdauung','Photosynthese','Diffusion','Verbrennung'],a:1},{q:'Welche Sprache wird hauptsächlich in Großbritannien gesprochen?',o:['Englisch','Spanisch','Französisch','Italienisch'],a:0}];renderQuestion()}
function renderQuestion(){const area=$('#quizArea');if(quizIndex>=quizQuestions.length){area.innerHTML='<div class="quiz-card"><h2>Quiz abgeschlossen 🎉</h2><p>Du hast <b>'+quizScore+' von '+quizQuestions.length+'</b> richtig beantwortet.</p><button class="primary" onclick="startQuiz()">Nochmal spielen</button></div>';addMinutes(3);return}const q=quizQuestions[quizIndex];area.innerHTML='<div class="quiz-card"><span class="eyebrow">FRAGE '+(quizIndex+1)+' / '+quizQuestions.length+'</span><h2>'+q.q+'</h2>'+q.o.map((x,i)=>'<button class="option" onclick="answerQuiz('+i+',this)">'+x+'</button>').join('')+'</div>'}
function answerQuiz(i,btn){const q=quizQuestions[quizIndex];$$('.option').forEach(b=>b.disabled=true);if(i===q.a){btn.classList.add('correct');quizScore++}else{btn.classList.add('wrong');$$('.option')[q.a].classList.add('correct')}setTimeout(()=>{quizIndex++;renderQuestion()},750)}
function renderAll(){renderWorksheets();renderSaved()}renderAll();